name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Opt into Node 24 for all JS actions
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: "Notify Vercel"
        if: github.event_name == 'pull_request'
        uses: "vercel/repository-dispatch/actions/status@v1"
        with:
          name: "Vercel - sahilcodex: build"
          github_token: ${{ github.token }}
